### ISSUE TITLE
Calling "Sparkle::getInstance ().start()" doesn't... well, start, with Sparkle 2

### ISSUE THREAD

**Issue by jrlanglois** [christophe-calmejane/sparkleHelper#2]
See title. Xcode throws this issue:

> [Sparkle] Error: checkForUpdatesInBackground - updater hasn't been started yet. Please call -startUpdater: first

The reason for needing Sparkle 2 is that the old Sparkle doesn't support macOS ARM.

**Comment by christophe-calmejane** [comment]
Not needed, see the [Changelog](https://github.com/sparkle-project/Sparkle/releases/tag/1.24.0) of Sparkle since v1.24.0:

> This release contains Universal framework compatible with both Intel and Apple Silicon (arm64/M1) Macs.

I'm using the universal binary without any issue since last May.

Currently only supporting Sparkle v1.x as specified in the [3rdparty README](https://github.com/christophe-calmejane/sparkleHelper/blob/main/3rdparty/sparkle/README.md)

**Comment by jrlanglois** [comment]
Just linking this here in case anybody ever needs it. Thanks for the education!

https://github.com/sparkle-project/Sparkle/releases/tag/1.24.0
